//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "assistant_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u8,
    pub tool_calling_provider: ToolCallingProvider,
    pub tool_calling_model: String,
    pub stt_model: String,
    pub stt_language: String,
    pub device_id: String,
    pub enable_on_start: bool,
    pub vad_threshold: f32,
    pub wake_threshold: f32,
    pub silence_hangover_frames: u32,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Eq, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum ToolCallingProvider {
    #[sea_orm(string_value = "Gemini")]
    Gemini,
    #[sea_orm(string_value = "Local")]
    Local,
}
