//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{alerts::Alert, donations::Media, rewards::Platform};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "assistant_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: AssistantActionType,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: AssistantActionData,
    #[sea_orm(uniq)]
    pub message_id: Uuid,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct AssistantAction {
    pub id: Uuid,
    pub r#type: AssistantActionType,
    pub data: AssistantActionData,
    pub message_id: Uuid,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum AssistantActionType {
    #[sea_orm(string_value = "BanUser")]
    BanUser,
    #[sea_orm(string_value = "UnbanUser")]
    UnbanUser,
    #[sea_orm(string_value = "PlayAlert")]
    PlayAlert,
    #[sea_orm(string_value = "PinMessage")]
    PinMessage,
    #[sea_orm(string_value = "ChangeChannelTitle")]
    ChangeChannelTitle,
    #[sea_orm(string_value = "ChangeChannelCategory")]
    ChangeChannelCategory,
    #[sea_orm(string_value = "AddFollowMode")]
    AddFollowMode,
    #[sea_orm(string_value = "RemoveFollowMode")]
    RemoveFollowMode,
    #[sea_orm(string_value = "AddEmotesMode")]
    AddEmotesMode,
    #[sea_orm(string_value = "RemoveEmotesMode")]
    RemoveEmotesMode,
    #[sea_orm(string_value = "AddSubscribersMode")]
    AddSubscribersMode,
    #[sea_orm(string_value = "RemoveSubscribersMode")]
    RemoveSubscribersMode,
    #[sea_orm(string_value = "AddSlowMode")]
    AddSlowMode,
    #[sea_orm(string_value = "RemoveSlowMode")]
    RemoveSlowMode,
    #[sea_orm(string_value = "PlayMedia")]
    PlayMedia,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(untagged)]

pub enum AssistantActionData {
    BanUser(UserData),
    UnbanUser(UserData),
    PlayAlert(Alert),
    PinMessage(PinedMessageData),
    ChangeChannel(ChanelData),
    UpdateChatSettings(ChatSettingsData),
    PlayMedia(MediaData),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UserData {
    pub name: String,
    pub platform: Platform,
    pub id: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PinedMessageData {
    pub message: String,
    pub platform: Platform,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChanelData {
    pub title: Option<String>,
    pub platform: Platform,
    pub category: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ChatSettingsData {
    pub platform: Platform,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MediaData {
    pub media: Media,
    pub title: String,
}
