//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{alerts::Alert, rewards::Platform};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "assistant_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: AssistantActionType,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: AssistantActionData,
    #[sea_orm(uniq)]
    pub message_id: Uuid,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct AssistantAction {
    pub id: Uuid,
    pub r#type: AssistantActionType,
    pub data: AssistantActionData,
    pub message_id: Uuid,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum AssistantActionType {
    #[sea_orm(string_value = "BanUser")]
    BanUser,
    #[sea_orm(string_value = "PlayAlert")]
    PlayAlert,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(untagged)]

pub enum AssistantActionData {
    BanUser(BanUserData),
    PlayAlert(Alert),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BanUserData {
    pub name: String,
    pub platform: Platform,
    pub id: String,
}
