//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use std::collections::HashMap;

use sea_orm::entity::prelude::*;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use serde_json::{json, Error};

use crate::alerts::{TtsSettings, TtsType};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "assistant_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u8,
    pub tool_calling_provider: ToolCallingProvider,
    #[sea_orm(column_type = "JsonBinary")]
    pub tool_calling_model: ToolCallingModel,
    pub stt_model: String,
    pub stt_language: String,
    pub device_id: String,
    pub enable_on_start: bool,
    pub vad_threshold: f32,
    pub wake_threshold: f32,
    pub silence_hangover_frames: u32,
    #[sea_orm(column_type = "JsonBinary")]
    pub tools: Tools,
    pub max_tokens: u32,
    pub tts_volume: u32,
    pub tts_type: TtsType,
    #[sea_orm(column_type = "JsonBinary")]
    pub tts_settings: Option<TtsSettings>,
    pub max_chars: u32,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Eq, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum ToolCallingProvider {
    #[sea_orm(string_value = "Gemini")]
    Gemini,
    #[sea_orm(string_value = "Claude")]
    Claude,
    #[sea_orm(string_value = "OpenAI")]
    OpenAI,
    #[sea_orm(string_value = "Local")]
    Local,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct ToolCallingModel {
    pub id: String,
    pub display_name: String,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult, Default)]
pub struct Tools(pub Vec<Tool>);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Tool {
    pub r#type: String, // "function"
    pub function: FunctionDef,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FunctionDef {
    pub name: String,
    pub description: String,
    pub parameters: Parameters,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Parameters {
    pub r#type: String, // "object"
    #[serde(default)]
    pub properties: HashMap<String, PropertySchema>,
    #[serde(default)]
    pub required: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PropertySchema {
    pub r#type: String, // "string"
    pub description: String,
}

impl Tool {
    pub fn get_tools<T: DeserializeOwned>() -> Result<Vec<T>, Error> {
        let tools = serde_json::from_value(json!([
        {
            "type": "function",
            "function": {
                "name": "play_alert",
                "description": "Play alert.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "Alert name"
                        }
                    },
                    "required": ["name"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "pin_message",
                "description": "Pin a message in a channel.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "User message."
                        },
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        },
                    },
                    "required": ["message","platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "ban_user",
                "description": "Ban a user from the channel.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "username": {
                            "type": "string",
                            "description": "User name in channel."
                        },
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        },
                         "duration": {
                            "type": "string",
                            "description": "Timeout duration in seconds for Twitch and in minutes for Kick. Omit this field to ban the user indefinitely."
                        }
                    },
                    "required": ["username","platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "unban_user",
                "description": "Unban user in channel.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "username": {
                            "type": "string",
                            "description": "User name in channel."
                        },
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["username","platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "skip_alert",
                "description": "Skip playing alert.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "skip_media",
                "description": "Skip playing media.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "skip_tts",
                "description": "Skip playing TTS.",
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": []
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "change_channel_title",
                "description": "Change chanel title.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "Chanel title."
                        },
                          "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform","title"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "change_channel_category",
                "description": "Change the channel category on Twitch or Kick.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "category": {
                            "type": "string",
                            "description": "The category to set for the channel, such as Just Chatting, Minecraft, or Fortnite."
                        },
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform","category"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "delete_chat_messages",
                "description": "Delete messages and clear chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "on_followers_mode",
                "description": "Enable followers-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "off_followers_mode",
                "description": "Disable followers-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
         {
            "type": "function",
            "function": {
                "name": "on_emotes_mode",
                "description": "Enable emotes-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "off_emotes_mode",
                "description": "Disable emotes-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
         {
            "type": "function",
            "function": {
                "name": "on_subscribers_mode",
                "description": "Enable subscribers-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "off_subscribers_mode",
                "description": "Disable subscribers-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
         {
            "type": "function",
            "function": {
                "name": "on_slow_mode",
                "description": "Enable slow-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "off_slow_mode",
                "description": "Disable slow-only mode for the chat.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "platform": {
                            "type": "string",
                            "description": "Twitch, Kick, Youtube."
                        }
                    },
                    "required": ["platform"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "play_media",
                "description": "Play a YouTube song or video.",
                 "parameters": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "The name or title of the YouTube song or video to play."
                        }
                    },
                    "required": ["name"]
                }
            }
        },
        ]))?;
        Ok(tools)
    }
}
