//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "assistant_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u8,
    pub provider: AssistantProvider,
    pub model: String,
    pub language: String,
    pub device_id: String,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Eq, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum AssistantProvider {
    #[sea_orm(string_value = "Gemini")]
    Gemini,
}
