//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "commands")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub source: Source,
    #[sea_orm(column_type = "JsonBinary")]
    pub action: Action,
    pub source_type: CommandSourceType,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Command {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub source: Source,
    pub action: Action,
    pub source_type: CommandSourceType,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(untagged)]
pub enum Source {
    Chat(ChatSource),
    Custom(CustomSource),
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum CommandSourceType {
    #[sea_orm(string_value = "Chat")]
    Chat,
    #[sea_orm(string_value = "Custom")]
    Custom,
    #[sea_orm(string_value = "None")]
    None,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct ChatSource {
    pub trigger: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct CustomSource {
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct Action {
    pub chat_bot: Option<ChatBotAction>,
    pub alert: Option<AlertAction>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct ChatBotAction {
    pub message: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct AlertAction {
    pub message: String,
}
