//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::rewards::Platform;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "commands")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub chat: Option<ChatSource>,
    #[sea_orm(column_type = "JsonBinary")]
    pub timer: Option<TimerSource>,
    #[sea_orm(column_type = "JsonBinary")]
    pub chat_bot: Option<ChatBotAction>,
    #[sea_orm(has_one)]
    pub alert: HasOne<super::alerts::Entity>,
    pub source_type: CommandSourceType,
    pub is_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Command {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub chat: Option<ChatSource>,
    pub timer: Option<TimerSource>,
    pub chat_bot: Option<ChatBotAction>,
    pub source_type: CommandSourceType,
    pub is_enabled: bool,
    #[sea_orm(nested)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alert: Option<super::alerts::Alert>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum CommandSourceType {
    #[sea_orm(string_value = "Chat")]
    Chat,
    #[sea_orm(string_value = "Timer")]
    Timer,
    #[sea_orm(string_value = "None")]
    None,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct ChatSource {
    pub trigger: String,
    pub platforms: Vec<Platform>,
    pub user_levels: Vec<UserLevel>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct TimerSource {
    pub message: String,
    pub mins_passed: u64,
    pub lines_passed: u64,
    pub post_type: PostType,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Eq, FromJsonQueryResult)]
pub struct ChatBotAction {
    pub message: String,
    pub replay: bool,
    pub platforms: Vec<Platform>,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub enum UserLevel {
    Streamer,
    Moderator,
    Vip,
    Subscriber,
    Anyone,
}
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub enum PostType {
    Normal,
    Announcement,
}
