//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{donations::Media, rewards::Platform};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "commands_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_name: String,
    pub user_input: Option<String>,
    pub command_id: Uuid,
    pub command_name: String,
    pub platform: Option<Platform>,
    #[sea_orm(column_type = "JsonBinary")]
    pub media: Option<Media>,
    #[sea_orm(uniq)]
    pub message_id: Uuid,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
    #[sea_orm(column_type = "JsonBinary")]
    pub alert: Option<super::alerts::Alert>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct CommandAction {
    pub id: Uuid,
    pub user_name: String,
    pub user_input: Option<String>,
    pub command_id: Uuid,
    pub command_name: String,
    pub message_id: Uuid,
    pub platform: Option<Platform>,
    pub media: Option<Media>,
    pub alert: Option<super::alerts::Alert>,
}

impl ActiveModelBehavior for ActiveModel {}
