//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::services::ServiceType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "followers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub service_id: String,
    pub user_name: String,
    pub user_id: String,
    #[sea_orm(uniq)]
    pub message_id: String,
    pub played: bool,
    pub service: ServiceType,
    pub followed_at: i64,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Follow {
    pub id: String,
    pub service_id: String,
    pub user_name: String,
    pub user_id: String,
    pub message_id: String,
    pub played: bool,
    pub service: ServiceType,
    pub followed_at: i64,
}

impl ActiveModelBehavior for ActiveModel {}
