//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::services::ServiceType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "raids")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub service_id: String,
    pub from_broadcaster_user_name: String,
    pub from_broadcaster_user_id: String,
    #[sea_orm(uniq)]
    pub message_id: Uuid,
    pub played: bool,
    pub viewers: u32,
    pub service: ServiceType,
    pub created_at: i64,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
    #[sea_orm(column_type = "JsonBinary")]
    pub alert: Option<super::alerts::Alert>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Raid {
    pub id: Uuid,
    pub service_id: String,
    pub from_broadcaster_user_name: String,
    pub from_broadcaster_user_id: String,
    pub message_id: Uuid,
    pub played: bool,
    pub viewers: u32,
    pub service: ServiceType,
    pub created_at: i64,
    pub alert: Option<super::alerts::Alert>,
}

impl ActiveModelBehavior for ActiveModel {}
