//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{
    commands_actions::Tts,
    donations::Media,
    rewards::{Platform, RewardType},
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "redemptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: String,
    pub user_name: String,
    pub user_input: Option<String>,
    pub external_id: String,
    pub reward_id: Uuid,
    pub title: String,
    pub description: Option<String>,
    pub cost: i64,
    pub platform: Platform,
    pub r#type: RewardType,
    pub points_currency_ratio: f32,
    #[sea_orm(column_type = "JsonBinary")]
    pub media: Option<Media>,
    #[sea_orm(column_type = "JsonBinary")]
    pub tts: Option<Tts>,
    #[sea_orm(uniq)]
    pub message_id: Uuid,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
    #[sea_orm(column_type = "JsonBinary")]
    pub alert: Option<super::alerts::Alert>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Redemption {
    pub id: Uuid,
    pub user_id: String,
    pub user_name: String,
    pub user_input: Option<String>,
    pub external_id: String,
    pub reward_id: Uuid,
    pub title: String,
    pub message_id: Uuid,
    pub description: Option<String>,
    pub cost: i64,
    pub platform: Platform,
    pub r#type: RewardType,
    pub points_currency_ratio: f32,
    pub media: Option<Media>,
    pub tts: Option<Tts>,
    pub alert: Option<super::alerts::Alert>,
}

impl ActiveModelBehavior for ActiveModel {}
