//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::{
    alerts::AlertVariant,
    donations::Media,
    rewards::{Platform, RewardType},
};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "redemptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub user_id: String,
    pub user_name: String,
    pub user_input: Option<String>,
    pub external_id: String,
    pub reward_id: String,
    pub title: String,
    pub description: Option<String>,
    pub cost: i64,
    pub platform: Platform,
    pub r#type: RewardType,
    pub points_currency_ratio: f32,
    pub media: Option<Media>,
    pub image: Option<String>,
    pub audio: Option<String>,
    pub video: Option<String>,
    pub alert_variant: AlertVariant,
    pub audio_volume: u32,
    pub video_volume: u32,
    pub duration: u32,
    pub delay: u32,
    #[sea_orm(uniq)]
    pub message_id: String,
    #[sea_orm(belongs_to, from = "message_id", to = "id")]
    pub message: HasOne<super::messages::Entity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Redemption {
    pub id: String,
    pub user_id: String,
    pub user_name: String,
    pub user_input: Option<String>,
    pub external_id: String,
    pub reward_id: String,
    pub title: String,
    pub message_id: String,
    pub description: Option<String>,
    pub cost: i64,
    pub platform: Platform,
    pub r#type: RewardType,
    pub points_currency_ratio: f32,
    pub media: Option<Media>,
    pub image: Option<String>,
    pub audio: Option<String>,
    pub video: Option<String>,
    pub alert_variant: AlertVariant,
    pub audio_volume: u32,
    pub video_volume: u32,
    pub duration: u32,
    pub delay: u32,
}

impl ActiveModelBehavior for ActiveModel {}
