//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rewards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub platform: Platform,
    pub r#type: RewardType,
    pub external_id: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub cost: i64,
    pub background_color: String,
    pub is_user_input_required: bool,
    pub points_currency_ratio: f32,
    pub is_enabled: bool,
    pub is_max_per_stream_enabled: Option<bool>,
    pub max_per_stream: Option<i64>,
    pub is_max_per_user_per_stream_enabled: Option<bool>,
    pub max_per_user_per_stream: Option<i64>,
    pub is_global_cooldown_enabled: Option<bool>,
    pub global_cooldown_seconds: Option<i64>,
    pub should_redemptions_skip_request_queue: Option<bool>,
    #[sea_orm(has_one)]
    pub alert: HasOne<super::alerts::Entity>,
}

#[derive(Debug, Clone, Serialize, Deserialize, DerivePartialModel)]
#[sea_orm(entity = "Entity")]
pub struct Reward {
    pub id: Uuid,
    pub platform: Platform,
    pub r#type: RewardType,
    pub external_id: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub cost: i64,
    pub background_color: String,
    pub is_user_input_required: bool,
    pub points_currency_ratio: f32,
    pub is_enabled: bool,
    pub is_max_per_stream_enabled: Option<bool>,
    pub max_per_stream: Option<i64>,
    pub is_max_per_user_per_stream_enabled: Option<bool>,
    pub max_per_user_per_stream: Option<i64>,
    pub is_global_cooldown_enabled: Option<bool>,
    pub global_cooldown_seconds: Option<i64>,
    pub should_redemptions_skip_request_queue: Option<bool>,
    #[sea_orm(nested)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alert: Option<super::alerts::Alert>,
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum Platform {
    #[sea_orm(string_value = "Twitch")]
    Twitch,
    #[sea_orm(string_value = "Kick")]
    Kick,
}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Eq)]
#[sea_orm(rs_type = "String", db_type = "Text")]
pub enum RewardType {
    #[sea_orm(string_value = "Media")]
    Media,
    #[sea_orm(string_value = "Auction")]
    Auction,
    #[sea_orm(string_value = "Alert")]
    Alert,
}
