use serde::Serialize;

#[derive(Serialize, Clone, Debug)]
pub enum AppEvent {
    Message,
    MediaMessage,
    SkipAlert,
    SkipPlayingAlert,
    SkipPlayingMedia,
    ReplayAlert,
    AlertPlaying,
    AlertPlayed,
    MediaPlaying,
    MediaPaused,
    PauseMedia,
    MediaPlayed,
    MediaEnd,
    MediaError,
    PlayMedia,
    SkipMedia,
    ReplayMedia,
    Alerts,
    MakeAudioError,
    Settings,
    MediaSettings,
    StartAucFighterMatch,
    PauseAucFighterMatch,
    ResumeAucFighterMatch,
    AucFighterMatchEnd,
    AucFighterMatchPlaying,
    AucFighterMatchPaused,
    UpdateAucFighterMatch,
    CancelAucFighterMatch,
    AucFighterSettings,
    TestAlert,
    TwitchRewardRedemptionAdd,
    Goal,
    CreateDonationAccount,
    WidgetViewStorage,
    WidgetControlStorage,
}
impl AppEvent {
    pub fn as_str(e: AppEvent) -> &'static str {
        match e {
            AppEvent::Message => "Message",
            AppEvent::MediaMessage => "MediaMessage",
            AppEvent::SkipAlert => "SkipAlert",
            AppEvent::SkipPlayingAlert => "SkipPlayingAlert",
            AppEvent::SkipMedia => "SkipMedia",
            AppEvent::SkipPlayingMedia => "SkipPlayingMedia",
            AppEvent::AlertPlaying => "AlertPlaying",
            AppEvent::MediaPlaying => "MediaPlaying",
            AppEvent::MediaPaused => "MediaPaused",
            AppEvent::PauseMedia => "PauseMedia",
            AppEvent::MediaEnd => "MediaEnd",
            AppEvent::MediaError => "MediaError",
            AppEvent::ReplayMedia => "ReplayMedia",
            AppEvent::PlayMedia => "PlayMedia",
            AppEvent::MediaPlayed => "MediaPlayed",
            AppEvent::AlertPlayed => "AlertPlayed",
            AppEvent::MakeAudioError => "MakeAudioError",
            AppEvent::Alerts => "Alerts",
            AppEvent::ReplayAlert => "AlertsSettings",
            AppEvent::Settings => "Settings",
            AppEvent::MediaSettings => "MediaSettings",
            AppEvent::StartAucFighterMatch => "StartAucFighterMatch",
            AppEvent::PauseAucFighterMatch => "PauseAucFighterMatch",
            AppEvent::ResumeAucFighterMatch => "ResumeAucFighterMatch",
            AppEvent::AucFighterMatchEnd => "AucFighterMatchEnd",
            AppEvent::AucFighterMatchPlaying => "AucFighterMatchPlaying",
            AppEvent::AucFighterMatchPaused => "AucFighterMatchPaused",
            AppEvent::UpdateAucFighterMatch => "UpdateAucFighterMatch",
            AppEvent::CancelAucFighterMatch => "CancelAucFighterMatch",
            AppEvent::AucFighterSettings => "AucFighterSettings",
            AppEvent::TestAlert => "TestAlert",
            AppEvent::Goal => "Goal",
            AppEvent::TwitchRewardRedemptionAdd => "TwitchRewardRedemptionAdd",
            AppEvent::CreateDonationAccount => "CreateDonationAccount",
            AppEvent::WidgetViewStorage => "WidgetViewStorage",
            AppEvent::WidgetControlStorage => "WidgetControlStorage",
        }
    }
}
